name: Main - CD
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  test_global:
    name: Global
    uses: ./.github/workflows/test__global.yml
    secrets: inherit

  deploy_book:
    name: Book
    needs: [test_global]
    uses: ./.github/workflows/deploy__book.yml
    secrets: inherit
