name: Test - global
on:
  workflow_call:

jobs:
  format-nix:
    name: Format Nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.format-nix
      - run: git diff --exit-code

  format-sh:
    name: Format Shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.format-sh
      - run: git diff --exit-code

  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.lint-yaml

  lint-gh-actions:
    name: Lint GitHub Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.lint-gh-actions

  lint-md:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.lint-md

  check-generated-files:
    name: Check Generated Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.check-generated-files

  format-ts:
    name: Format TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --immutable
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.format-ts
      - run: git diff --exit-code

  lint-ts:
    name: Lint TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install --immutable
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . root.lint-ts

  validate-terraform-repository:
    name: Validate Terraform (repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . terraform.modules.repository.validate

  validate-terraform-book:
    name: Validate Terraform (book)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-nix
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix --print-build-logs run --file . terraform.modules.book.validate
